# Generated by Django 5.2.1 on 2025-05-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('landline', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن ثابت')),
                ('office_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن دفتر')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='موبایل')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='سمت شغلی')),
                ('workplace', models.CharField(blank=True, max_length=200, null=True, verbose_name='محل کار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطبین',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
